### ISSUE TITLE
 Создать нормальное описание проекта

### ISSUE THREAD

**Issue by LiberiaSus** [mgiks/TextAdventure#1]
Я предлагаю написать как-то так: "Увлекательная text-based RPG, в которой сущетвует невероятная вариативность сюжета, разворачивающаяся в fantasy мире. В отличие от Starfileld, в ней гораздо меньше багов, и она не требует покупать новый компьютер, будет достаточно даже Thinkpad 700T. Это ваша уникальная возможность почувствовать себя" и так далее. Вот тогда будет нормально. Ещё круче если добавить ИИ картинку в качестве баннера

**Comment by mgiks** [comment]
Отличное предложение
Рассмотрим когда Bethesda выпустит хорошую игру
